<?php require 'templates/header.phtml' ?>

<?php if (isset($_SESSION['USER_ID']) && $_SESSION['USER_ID']) : ?>
    <?php require 'templates/form_add_author.phtml' ?>
<?php endif ?>

<table class="table">

    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Autores</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($authors as $author) : ?>
            <tr>
                <th scope="row"><?= $author->id_author ?></th>
                <td><?= $author->name ?></td>

                <td class="dropdown">
                    <button class="btn btn-success dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Ver Libros</button>
                    <ul class="dropdown-menu text-nowrap p-3" aria-labelledby=" dropdownMenuButton"">
                        <?php foreach ($books as $book) : ?>
                            <?php if ($book->id_author == $author->id_author) : ?>
                                <li><?= $book->title ?></li>
                            <?php endif ?>
                        <?php endforeach ?>
                    </ul>
                </td>

                <?php if (isset($_SESSION['USER_ID']) && $_SESSION['USER_ID']) : ?>
                    <td><a href='editarAutor/<?= $author->id_author ?>' type='button' class='btn btn-warning'>Editar</a></td>
                    <td><a href='eliminarAutor/<?= $author->id_author ?>' type='button' class='btn btn-danger'>Borrar</a></td>
                <?php endif ?>
            </tr>
        <?php endforeach ?>
    </tbody>

</table>

<p class=" mt-3 fst-italic"><b>Mostrando <?= $count ?> autores</b></p>

<?php require 'templates/footer.phtml' ?>