<?php require 'templates/header.phtml' ?>

<?php if (isset($_SESSION['USER_ID']) && $_SESSION['USER_ID']) : ?>
    <?php require 'templates/form_add_book.phtml' ?>
<?php endif ?>

<table class="table">

    <thead>
        <tr class="text-nowrap">
            <th scope="col">ID</th>
            <th scope="col">Título</th>
            <th scope="col">Año de Publicación</th>
            <th scope="col">Autor</th>
            <th scope="col">Sinopsis</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($books as $book) : ?>
            <tr>
                <th scope="row"><?= $book->id_book ?></th>
                <td><?= $book->title ?></td>
                <td><?= $book->publication_date ?></td>

                <td class="dropdown">
                    <button class="btn btn-success dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Ver</button>
                    <ul class="dropdown-menu text-nowrap p-3" aria-labelledby=" dropdownMenuButton"">
                        <li><span class=" fw-bold fst-italic">Nombre </span><?= $book->author->name ?></li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li><span class=" fw-bold fst-italic">ID Autor </span><?= $book->author->id_author ?></li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li><span class="fw-bold fst-italic">Libros</span></li>
                        <?php foreach ($books as $book_author) : ?>
                            <?php if ($book->author->id_author == $book_author->author->id_author) : ?>
                                <li><?= $book_author->title ?></li>
                            <?php endif ?>
                        <?php endforeach ?>
                    </ul>
                </td>

                <td class=" text-center"><?= $book->synopsis ?></td>
                <?php if (isset($_SESSION['USER_ID']) && $_SESSION['USER_ID']) : ?>
                    <td><a href='editarLibro/<?= $book->id_book ?>' type='button' class='btn btn-warning'>Editar</a></td>
                    <td><a href='eliminarLibro/<?= $book->id_book ?>' type='button' class='btn btn-danger'>Borrar</a></td>
                <?php endif ?>
            </tr>
        <?php endforeach ?>
    </tbody>

</table>

<p class="mt-3 fst-italic"><b>Mostrando <?= $count ?> libros</b></p>

<?php require 'templates/footer.phtml' ?>