    </main>

    <img src="./img/logo.jpg" alt="" srcset="" class="mx-auto d-block w-25 rounded-circle img-fluid shadow-lg">

    <footer class="d-flex flex-wrap justify-content-center align-items-center p-3 mt-3 border-top">
        <div class="align-items-center row">
            <span class="text-muted text-center">Echazú, Candela Azul y Fernández, Daniela Antonella</span>
            <span class="text-muted text-center">2023 TPE WEB II TUDAI, UNICEN</span>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    </body>

    </html>