<div class="text-primary mb-3 p-3 border border-primary">
    <p class="text-primary fw-bold fst-italic">Añadir Autor</p>

    <form action="agregarAutor" method="POST">

        <div class="row">
            <div class="col-3">
                <div class="form-group">
                    <label>Nombre</label>
                    <input required name="name" type="text" class="form-control">
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary mt-2">Añadir</button>
    </form>
</div>