<div class="text-primary mb-3 p-3 border border-primary">
    <p class="fw-bold fst-italic">Añadir Libro</p>

    <form action="agregarLibro" method="POST">
        <div class="row">
            <div class="col-3">
                <div class="form-group">
                    <label>Título</label>
                    <input required name="title" type="text" class="form-control" required>
                </div>
            </div>

            <div class="col-9">
                <div class="form-group">
                    <label>Año de Publicación</label>
                    <input required name="publication_date" type="number" class="form-control" required>
                </div>
            </div>

            <div class="col-3">
                <div class="form-group">
                    <label>Autor</label>
                    <select name="id_author" class="form-control">
                        <?php foreach ($authors as $author) : ?>
                            <option value="<?= $author->id_author ?>"><?= $author->name ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label>Sinopsis</label>
                <textarea name="synopsis" class="form-control" rows="3" required></textarea>
            </div>
        </div>

        <button type="submit" class="btn btn-primary mt-2">Añadir</button>
    </form>
</div>