<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>La Biblioteca del Horror</title>
    <link rel="icon" type="image/png" href="./img/logo.jpg">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
    <header>
        <nav class=" navbar navbar-expand-lg bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold text-white" href="">La Biblioteca del Horror</a>
            </div>
        </nav>
    </header>

    <main class="container mt-3">