<?php require 'templates/header.phtml' ?>

<div class="text-primary m-5 p-3 w-25 mx-auto border border-primary">
    <p class="fw-bold fst-italic">Login</p>

    <form method="POST" action="auth">
        <div class="form-group">
            <label for="email">Usuario</label>
            <input type="text" class="form-control" id="user" name="user" required>
        </div>
        <div class="form-group">
            <label for="password">Contraseña</label>
            <input type="password" class="form-control" id="password" name="password" required>
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger mt-3' role='alert'>
                <?= $error ?>
            </div>
        <?php endif ?>

        <button type="submit" class="btn btn-primary mt-3 mx-auto d-block">Ingresar</button>
    </form>
</div>

<?php require 'templates/footer.phtml' ?>